#ifndef SYSNAME_H
# define SYSNAME_H
#include <syscall.h>

// typedef struct  s_sysc
// {
//     char    *name;
//     char    *ret_type;
//     int     nb_params;
//     char    *type1;
//     char    *type2;
//     char    *type3;
//     char    *type4;
//     char    *type5;
//     char    *type6;
// }               t_sysc;
// t_sysc  sysc[] = {
//     [SYS_read] = {"read", "ssize_t", 3, "int", "void*", "size_t", 0, 0, 0}

char  *sysname[] = {
    [SYS_read] = "read",
    [SYS_write] = "write",
    [SYS_open] = "open",
    [SYS_close] = "close",
    [SYS_stat] = "stat",
    [SYS_fstat] = "fstat",
    [SYS_lstat] = "lstat",
    [SYS_poll] = "poll",
    [SYS_lseek] = "lseek",
    [SYS_mmap] = "mmap",
    [SYS_mprotect] = "mprotect",
    [SYS_munmap] = "munmap",
    [SYS_brk] = "brk",
    [SYS_rt_sigaction] = "rt_sigaction",
    [SYS_rt_sigprocmask] = "rt_sigprocmask",
    [SYS_rt_sigreturn] = "rt_sigreturn",
    [SYS_ioctl] = "ioctl",
    [SYS_pread64] = "pread64",
    [SYS_pwrite64] = "pwrite64",
    [SYS_readv] = "readv",
    [SYS_writev] = "writev",
    [SYS_access] = "access",
    [SYS_pipe] = "pipe",
    [SYS_select] = "select",
    [SYS_sched_yield] = "sched_yield",
    [SYS_mremap] = "mremap",
    [SYS_msync] = "msync",
    [SYS_mincore] = "mincore",
    [SYS_madvise] = "madvise",
    [SYS_shmget] = "shmget",
    [SYS_shmat] = "shmat",
    [SYS_shmctl] = "shmctl",
    [SYS_dup] = "dup",
    [SYS_dup2] = "dup2",
    [SYS_pause] = "pause",
    [SYS_nanosleep] = "nanosleep",
    [SYS_getitimer] = "getitimer",
    [SYS_alarm] = "alarm",
    [SYS_setitimer] = "setitimer",
    [SYS_getpid] = "getpid",
    [SYS_sendfile] = "sendfile",
    [SYS_socket] = "socket",
    [SYS_connect] = "connect",
    [SYS_accept] = "accept",
    [SYS_sendto] = "sendto",
    [SYS_recvfrom] = "recvfrom",
    [SYS_sendmsg] = "sendmsg",
    [SYS_recvmsg] = "recvmsg",
    [SYS_shutdown] = "shutdown",
    [SYS_bind] = "bind",
    [SYS_listen] = "listen",
    [SYS_getsockname] = "getsockname",
    [SYS_getpeername] = "getpeername",
    [SYS_socketpair] = "socketpair",
    [SYS_setsockopt] = "setsockopt",
    [SYS_getsockopt] = "getsockopt",
    [SYS_clone] = "clone",
    [SYS_fork] = "fork",
    [SYS_vfork] = "vfork",
    [SYS_execve] = "execve",
    [SYS_exit] = "exit",
    [SYS_wait4] = "wait4",
    [SYS_kill] = "kill",
    [SYS_uname] = "uname",
    [SYS_semget] = "semget",
    [SYS_semop] = "semop",
    [SYS_semctl] = "semctl",
    [SYS_shmdt] = "shmdt",
    [SYS_msgget] = "msgget",
    [SYS_msgsnd] = "msgsnd",
    [SYS_msgrcv] = "msgrcv",
    [SYS_msgctl] = "msgctl",
    [SYS_fcntl] = "fcntl",
    [SYS_flock] = "flock",
    [SYS_fsync] = "fsync",
    [SYS_fdatasync] = "fdatasync",
    [SYS_truncate] = "truncate",
    [SYS_ftruncate] = "ftruncate",
    [SYS_getdents] = "getdents",
    [SYS_getcwd] = "getcwd",
    [SYS_chdir] = "chdir",
    [SYS_fchdir] = "fchdir",
    [SYS_rename] = "rename",
    [SYS_mkdir] = "mkdir",
    [SYS_rmdir] = "rmdir",
    [SYS_creat] = "creat",
    [SYS_link] = "link",
    [SYS_unlink] = "unlink",
    [SYS_symlink] = "symlink",
    [SYS_readlink] = "readlink",
    [SYS_chmod] = "chmod",
    [SYS_fchmod] = "fchmod",
    [SYS_chown] = "chown",
    [SYS_fchown] = "fchown",
    [SYS_lchown] = "lchown",
    [SYS_umask] = "umask",
    [SYS_gettimeofday] = "gettimeofday",
    [SYS_getrlimit] = "getrlimit",
    [SYS_getrusage] = "getrusage",
    [SYS_sysinfo] = "sysinfo",
    [SYS_times] = "times",
    [SYS_ptrace] = "ptrace",
    [SYS_getuid] = "getuid",
    [SYS_syslog] = "syslog",
    [SYS_getgid] = "getgid",
    [SYS_setuid] = "setuid",
    [SYS_setgid] = "setgid",
    [SYS_geteuid] = "geteuid",
    [SYS_getegid] = "getegid",
    [SYS_setpgid] = "setpgid",
    [SYS_getppid] = "getppid",
    [SYS_getpgrp] = "getpgrp",
    [SYS_setsid] = "setsid",
    [SYS_setreuid] = "setreuid",
    [SYS_setregid] = "setregid",
    [SYS_getgroups] = "getgroups",
    [SYS_setgroups] = "setgroups",
    [SYS_setresuid] = "setresuid",
    [SYS_getresuid] = "getresuid",
    [SYS_setresgid] = "setresgid",
    [SYS_getresgid] = "getresgid",
    [SYS_getpgid] = "getpgid",
    [SYS_setfsuid] = "setfsuid",
    [SYS_setfsgid] = "setfsgid",
    [SYS_getsid] = "getsid",
    [SYS_capget] = "capget",
    [SYS_capset] = "capset",
    [SYS_rt_sigpending] = "rt_sigpending",
    [SYS_rt_sigtimedwait] = "rt_sigtimedwait",
    [SYS_rt_sigqueueinfo] = "rt_sigqueueinfo",
    [SYS_rt_sigsuspend] = "rt_sigsuspend",
    [SYS_sigaltstack] = "sigaltstack",
    [SYS_utime] = "utime",
    [SYS_mknod] = "mknod",
    [SYS_uselib] = "uselib",
    [SYS_personality] = "personality",
    [SYS_ustat] = "ustat",
    [SYS_statfs] = "statfs",
    [SYS_fstatfs] = "fstatfs",
    [SYS_sysfs] = "sysfs",
    [SYS_getpriority] = "getpriority",
    [SYS_setpriority] = "setpriority",
    [SYS_sched_setparam] = "sched_setparam",
    [SYS_sched_getparam] = "sched_getparam",
    [SYS_sched_setscheduler] = "sched_setscheduler",
    [SYS_sched_getscheduler] = "sched_getscheduler",
    [SYS_sched_get_priority_max] = "sched_get_priority_max",
    [SYS_sched_get_priority_min] = "sched_get_priority_min",
    [SYS_sched_rr_get_interval] = "sched_rr_get_interval",
    [SYS_mlock] = "mlock",
    [SYS_munlock] = "munlock",
    [SYS_mlockall] = "mlockall",
    [SYS_munlockall] = "munlockall",
    [SYS_vhangup] = "vhangup",
    [SYS_modify_ldt] = "modify_ldt",
    [SYS_pivot_root] = "pivot_root",
    [SYS__sysctl] = "_sysctl",
    [SYS_prctl] = "prctl",
    [SYS_arch_prctl] = "arch_prctl",
    [SYS_adjtimex] = "adjtimex",
    [SYS_setrlimit] = "setrlimit",
    [SYS_chroot] = "chroot",
    [SYS_sync] = "sync",
    [SYS_acct] = "acct",
    [SYS_settimeofday] = "settimeofday",
    [SYS_mount] = "mount",
    [SYS_umount2] = "umount2",
    [SYS_swapon] = "swapon",
    [SYS_swapoff] = "swapoff",
    [SYS_reboot] = "reboot",
    [SYS_sethostname] = "sethostname",
    [SYS_setdomainname] = "setdomainname",
    [SYS_iopl] = "iopl",
    [SYS_ioperm] = "ioperm",
    [SYS_create_module] = "create_module",
    [SYS_init_module] = "init_module",
    [SYS_delete_module] = "delete_module",
    [SYS_get_kernel_syms] = "get_kernel_syms",
    [SYS_query_module] = "query_module",
    [SYS_quotactl] = "quotactl",
    [SYS_nfsservctl] = "nfsservctl",
    [SYS_getpmsg] = "getpmsg",
    [SYS_putpmsg] = "putpmsg",
    [SYS_afs_syscall] = "afs_syscall",
    [SYS_tuxcall] = "tuxcall",
    [SYS_security] = "security",
    [SYS_gettid] = "gettid",
    [SYS_readahead] = "readahead",
    [SYS_setxattr] = "setxattr",
    [SYS_lsetxattr] = "lsetxattr",
    [SYS_fsetxattr] = "fsetxattr",
    [SYS_getxattr] = "getxattr",
    [SYS_lgetxattr] = "lgetxattr",
    [SYS_fgetxattr] = "fgetxattr",
    [SYS_listxattr] = "listxattr",
    [SYS_llistxattr] = "llistxattr",
    [SYS_flistxattr] = "flistxattr",
    [SYS_removexattr] = "removexattr",
    [SYS_lremovexattr] = "lremovexattr",
    [SYS_fremovexattr] = "fremovexattr",
    [SYS_tkill] = "tkill",
    [SYS_time] = "time",
    [SYS_futex] = "futex",
    [SYS_sched_setaffinity] = "sched_setaffinity",
    [SYS_sched_getaffinity] = "sched_getaffinity",
    [SYS_set_thread_area] = "set_thread_area",
    [SYS_io_setup] = "io_setup",
    [SYS_io_destroy] = "io_destroy",
    [SYS_io_getevents] = "io_getevents",
    [SYS_io_submit] = "io_submit",
    [SYS_io_cancel] = "io_cancel",
    [SYS_get_thread_area] = "get_thread_area",
    [SYS_lookup_dcookie] = "lookup_dcookie",
    [SYS_epoll_create] = "epoll_create",
    [SYS_epoll_ctl_old] = "epoll_ctl_old",
    [SYS_epoll_wait_old] = "epoll_wait_old",
    [SYS_remap_file_pages] = "remap_file_pages",
    [SYS_getdents64] = "getdents64",
    [SYS_set_tid_address] = "set_tid_address",
    [SYS_restart_syscall] = "restart_syscall",
    [SYS_semtimedop] = "semtimedop",
    [SYS_fadvise64] = "fadvise64",
    [SYS_timer_create] = "timer_create",
    [SYS_timer_settime] = "timer_settime",
    [SYS_timer_gettime] = "timer_gettime",
    [SYS_timer_getoverrun] = "timer_getoverrun",
    [SYS_timer_delete] = "timer_delete",
    [SYS_clock_settime] = "clock_settime",
    [SYS_clock_gettime] = "clock_gettime",
    [SYS_clock_getres] = "clock_getres",
    [SYS_clock_nanosleep] = "clock_nanosleep",
    [SYS_exit_group] = "exit_group",
    [SYS_epoll_wait] = "epoll_wait",
    [SYS_epoll_ctl] = "epoll_ctl",
    [SYS_tgkill] = "tgkill",
    [SYS_utimes] = "utimes",
    [SYS_vserver] = "vserver",
    [SYS_mbind] = "mbind",
    [SYS_set_mempolicy] = "set_mempolicy",
    [SYS_get_mempolicy] = "get_mempolicy",
    [SYS_mq_open] = "mq_open",
    [SYS_mq_unlink] = "mq_unlink",
    [SYS_mq_timedsend] = "mq_timedsend",
    [SYS_mq_timedreceive] = "mq_timedreceive",
    [SYS_mq_notify] = "mq_notify",
    [SYS_mq_getsetattr] = "mq_getsetattr",
    [SYS_kexec_load] = "kexec_load",
    [SYS_waitid] = "waitid",
    [SYS_add_key] = "add_key",
    [SYS_request_key] = "request_key",
    [SYS_keyctl] = "keyctl",
    [SYS_ioprio_set] = "ioprio_set",
    [SYS_ioprio_get] = "ioprio_get",
    [SYS_inotify_init] = "inotify_init",
    [SYS_inotify_add_watch] = "inotify_add_watch",
    [SYS_inotify_rm_watch] = "inotify_rm_watch",
    [SYS_migrate_pages] = "migrate_pages",
    [SYS_openat] = "openat",
    [SYS_mkdirat] = "mkdirat",
    [SYS_mknodat] = "mknodat",
    [SYS_fchownat] = "fchownat",
    [SYS_futimesat] = "futimesat",
    [SYS_newfstatat] = "newfstatat",
    [SYS_unlinkat] = "unlinkat",
    [SYS_renameat] = "renameat",
    [SYS_linkat] = "linkat",
    [SYS_symlinkat] = "symlinkat",
    [SYS_readlinkat] = "readlinkat",
    [SYS_fchmodat] = "fchmodat",
    [SYS_faccessat] = "faccessat",
    [SYS_pselect6] = "pselect6",
    [SYS_ppoll] = "ppoll",
    [SYS_unshare] = "unshare",
    [SYS_set_robust_list] = "set_robust_list",
    [SYS_get_robust_list] = "get_robust_list",
    [SYS_splice] = "splice",
    [SYS_tee] = "tee",
    [SYS_sync_file_range] = "sync_file_range",
    [SYS_vmsplice] = "vmsplice",
    [SYS_move_pages] = "move_pages",
    [SYS_utimensat] = "utimensat",
    [SYS_epoll_pwait] = "epoll_pwait",
    [SYS_signalfd] = "signalfd",
    [SYS_timerfd_create] = "timerfd_create",
    [SYS_eventfd] = "eventfd",
    [SYS_fallocate] = "fallocate",
    [SYS_timerfd_settime] = "timerfd_settime",
    [SYS_timerfd_gettime] = "timerfd_gettime",
    [SYS_accept4] = "accept4",
    [SYS_signalfd4] = "signalfd4",
    [SYS_eventfd2] = "eventfd2",
    [SYS_epoll_create1] = "epoll_create1",
    [SYS_dup3] = "dup3",
    [SYS_pipe2] = "pipe2",
    [SYS_inotify_init1] = "inotify_init1",
    [SYS_preadv] = "preadv",
    [SYS_pwritev] = "pwritev",
    [SYS_rt_tgsigqueueinfo] = "rt_tgsigqueueinfo",
    [SYS_perf_event_open] = "perf_event_open",
    [SYS_recvmmsg] = "recvmmsg",
    [SYS_fanotify_init] = "fanotify_init",
    [SYS_fanotify_mark] = "fanotify_mark",
    [SYS_prlimit64] = "prlimit64",
    [SYS_name_to_handle_at] = "name_to_handle_at",
    [SYS_open_by_handle_at] = "open_by_handle_at",
    [SYS_clock_adjtime] = "clock_adjtime",
    [SYS_syncfs] = "syncfs",
    [SYS_sendmmsg] = "sendmmsg",
    [SYS_setns] = "setns",
    [SYS_getcpu] = "getcpu",
    [SYS_process_vm_readv] = "process_vm_readv",
    [SYS_process_vm_writev] = "process_vm_writev",
    [SYS_kcmp] = "kcmp",
    [SYS_finit_module] = "finit_module",
    [SYS_sched_setattr] = "sched_setattr",
    [SYS_sched_getattr] = "sched_getattr",
    [SYS_renameat2] = "renameat2",
    [SYS_seccomp] = "seccomp",
    [SYS_getrandom] = "getrandom",
    [SYS_memfd_create] = "memfd_create",
    [SYS_kexec_file_load] = "kexec_file_load",
    [SYS_bpf] = "bpf",
    [SYS_execveat] = "execveat",
    [SYS_userfaultfd] = "userfaultfd",
    [SYS_membarrier] = "membarrier",
    [SYS_mlock2] = "mlock2",
};

#endif
/*
#define SYS__sysctl __NR__sysctl
#define SYS_accept __NR_accept
#define SYS_accept4 __NR_accept4
#define SYS_access __NR_access
#define SYS_acct __NR_acct
#define SYS_add_key __NR_add_key
#define SYS_adjtimex __NR_adjtimex
#define SYS_afs_syscall __NR_afs_syscall
#define SYS_alarm __NR_alarm
#define SYS_arch_prctl __NR_arch_prctl
#define SYS_bind __NR_bind
#define SYS_bpf __NR_bpf
#define SYS_brk __NR_brk
#define SYS_capget __NR_capget
#define SYS_capset __NR_capset
#define SYS_chdir __NR_chdir
#define SYS_chmod __NR_chmod
#define SYS_chown __NR_chown
#define SYS_chroot __NR_chroot
#define SYS_clock_adjtime __NR_clock_adjtime
#define SYS_clock_getres __NR_clock_getres
#define SYS_clock_gettime __NR_clock_gettime
#define SYS_clock_nanosleep __NR_clock_nanosleep
#define SYS_clock_settime __NR_clock_settime
#define SYS_clone __NR_clone
#define SYS_close __NR_close
#define SYS_connect __NR_connect
#define SYS_creat __NR_creat
#define SYS_create_module __NR_create_module
#define SYS_delete_module __NR_delete_module
#define SYS_dup __NR_dup
#define SYS_dup2 __NR_dup2
#define SYS_dup3 __NR_dup3
#define SYS_epoll_create __NR_epoll_create
#define SYS_epoll_create1 __NR_epoll_create1
#define SYS_epoll_ctl __NR_epoll_ctl
#define SYS_epoll_ctl_old __NR_epoll_ctl_old
#define SYS_epoll_pwait __NR_epoll_pwait
#define SYS_epoll_wait __NR_epoll_wait
#define SYS_epoll_wait_old __NR_epoll_wait_old
#define SYS_eventfd __NR_eventfd
#define SYS_eventfd2 __NR_eventfd2
#define SYS_execve __NR_execve
#define SYS_execveat __NR_execveat
#define SYS_exit __NR_exit
#define SYS_exit_group __NR_exit_group
#define SYS_faccessat __NR_faccessat
#define SYS_fadvise64 __NR_fadvise64
#define SYS_fallocate __NR_fallocate
#define SYS_fanotify_init __NR_fanotify_init
#define SYS_fanotify_mark __NR_fanotify_mark
#define SYS_fchdir __NR_fchdir
#define SYS_fchmod __NR_fchmod
#define SYS_fchmodat __NR_fchmodat
#define SYS_fchown __NR_fchown
#define SYS_fchownat __NR_fchownat
#define SYS_fcntl __NR_fcntl
#define SYS_fdatasync __NR_fdatasync
#define SYS_fgetxattr __NR_fgetxattr
#define SYS_finit_module __NR_finit_module
#define SYS_flistxattr __NR_flistxattr
#define SYS_flock __NR_flock
#define SYS_fork __NR_fork
#define SYS_fremovexattr __NR_fremovexattr
#define SYS_fsetxattr __NR_fsetxattr
#define SYS_fstat __NR_fstat
#define SYS_fstatfs __NR_fstatfs
#define SYS_fsync __NR_fsync
#define SYS_ftruncate __NR_ftruncate
#define SYS_futex __NR_futex
#define SYS_futimesat __NR_futimesat
#define SYS_get_kernel_syms __NR_get_kernel_syms
#define SYS_get_mempolicy __NR_get_mempolicy
#define SYS_get_robust_list __NR_get_robust_list
#define SYS_get_thread_area __NR_get_thread_area
#define SYS_getcpu __NR_getcpu
#define SYS_getcwd __NR_getcwd
#define SYS_getdents __NR_getdents
#define SYS_getdents64 __NR_getdents64
#define SYS_getegid __NR_getegid
#define SYS_geteuid __NR_geteuid
#define SYS_getgid __NR_getgid
#define SYS_getgroups __NR_getgroups
#define SYS_getitimer __NR_getitimer
#define SYS_getpeername __NR_getpeername
#define SYS_getpgid __NR_getpgid
#define SYS_getpgrp __NR_getpgrp
#define SYS_getpid __NR_getpid
#define SYS_getpmsg __NR_getpmsg
#define SYS_getppid __NR_getppid
#define SYS_getpriority __NR_getpriority
#define SYS_getrandom __NR_getrandom
#define SYS_getresgid __NR_getresgid
#define SYS_getresuid __NR_getresuid
#define SYS_getrlimit __NR_getrlimit
#define SYS_getrusage __NR_getrusage
#define SYS_getsid __NR_getsid
#define SYS_getsockname __NR_getsockname
#define SYS_getsockopt __NR_getsockopt
#define SYS_gettid __NR_gettid
#define SYS_gettimeofday __NR_gettimeofday
#define SYS_getuid __NR_getuid
#define SYS_getxattr __NR_getxattr
#define SYS_init_module __NR_init_module
#define SYS_inotify_add_watch __NR_inotify_add_watch
#define SYS_inotify_init __NR_inotify_init
#define SYS_inotify_init1 __NR_inotify_init1
#define SYS_inotify_rm_watch __NR_inotify_rm_watch
#define SYS_io_cancel __NR_io_cancel
#define SYS_io_destroy __NR_io_destroy
#define SYS_io_getevents __NR_io_getevents
#define SYS_io_setup __NR_io_setup
#define SYS_io_submit __NR_io_submit
#define SYS_ioctl __NR_ioctl
#define SYS_ioperm __NR_ioperm
#define SYS_iopl __NR_iopl
#define SYS_ioprio_get __NR_ioprio_get
#define SYS_ioprio_set __NR_ioprio_set
#define SYS_kcmp __NR_kcmp
#define SYS_kexec_file_load __NR_kexec_file_load
#define SYS_kexec_load __NR_kexec_load
#define SYS_keyctl __NR_keyctl
#define SYS_kill __NR_kill
#define SYS_lchown __NR_lchown
#define SYS_lgetxattr __NR_lgetxattr
#define SYS_link __NR_link
#define SYS_linkat __NR_linkat
#define SYS_listen __NR_listen
#define SYS_listxattr __NR_listxattr
#define SYS_llistxattr __NR_llistxattr
#define SYS_lookup_dcookie __NR_lookup_dcookie
#define SYS_lremovexattr __NR_lremovexattr
#define SYS_lseek __NR_lseek
#define SYS_lsetxattr __NR_lsetxattr
#define SYS_lstat __NR_lstat
#define SYS_madvise __NR_madvise
#define SYS_mbind __NR_mbind
#define SYS_membarrier __NR_membarrier
#define SYS_memfd_create __NR_memfd_create
#define SYS_migrate_pages __NR_migrate_pages
#define SYS_mincore __NR_mincore
#define SYS_mkdir __NR_mkdir
#define SYS_mkdirat __NR_mkdirat
#define SYS_mknod __NR_mknod
#define SYS_mknodat __NR_mknodat
#define SYS_mlock __NR_mlock
#define SYS_mlock2 __NR_mlock2
#define SYS_mlockall __NR_mlockall
#define SYS_mmap __NR_mmap
#define SYS_modify_ldt __NR_modify_ldt
#define SYS_mount __NR_mount
#define SYS_move_pages __NR_move_pages
#define SYS_mprotect __NR_mprotect
#define SYS_mq_getsetattr __NR_mq_getsetattr
#define SYS_mq_notify __NR_mq_notify
#define SYS_mq_open __NR_mq_open
#define SYS_mq_timedreceive __NR_mq_timedreceive
#define SYS_mq_timedsend __NR_mq_timedsend
#define SYS_mq_unlink __NR_mq_unlink
#define SYS_mremap __NR_mremap
#define SYS_msgctl __NR_msgctl
#define SYS_msgget __NR_msgget
#define SYS_msgrcv __NR_msgrcv
#define SYS_msgsnd __NR_msgsnd
#define SYS_msync __NR_msync
#define SYS_munlock __NR_munlock
#define SYS_munlockall __NR_munlockall
#define SYS_munmap __NR_munmap
#define SYS_name_to_handle_at __NR_name_to_handle_at
#define SYS_nanosleep __NR_nanosleep
#define SYS_newfstatat __NR_newfstatat
#define SYS_nfsservctl __NR_nfsservctl
#define SYS_open __NR_open
#define SYS_open_by_handle_at __NR_open_by_handle_at
#define SYS_openat __NR_openat
#define SYS_pause __NR_pause
#define SYS_perf_event_open __NR_perf_event_open
#define SYS_personality __NR_personality
#define SYS_pipe __NR_pipe
#define SYS_pipe2 __NR_pipe2
#define SYS_pivot_root __NR_pivot_root
#define SYS_poll __NR_poll
#define SYS_ppoll __NR_ppoll
#define SYS_prctl __NR_prctl
#define SYS_pread64 __NR_pread64
#define SYS_preadv __NR_preadv
#define SYS_prlimit64 __NR_prlimit64
#define SYS_process_vm_readv __NR_process_vm_readv
#define SYS_process_vm_writev __NR_process_vm_writev
#define SYS_pselect6 __NR_pselect6
#define SYS_ptrace __NR_ptrace
#define SYS_putpmsg __NR_putpmsg
#define SYS_pwrite64 __NR_pwrite64
#define SYS_pwritev __NR_pwritev
#define SYS_query_module __NR_query_module
#define SYS_quotactl __NR_quotactl
#define SYS_read __NR_read
#define SYS_readahead __NR_readahead
#define SYS_readlink __NR_readlink
#define SYS_readlinkat __NR_readlinkat
#define SYS_readv __NR_readv
#define SYS_reboot __NR_reboot
#define SYS_recvfrom __NR_recvfrom
#define SYS_recvmmsg __NR_recvmmsg
#define SYS_recvmsg __NR_recvmsg
#define SYS_remap_file_pages __NR_remap_file_pages
#define SYS_removexattr __NR_removexattr
#define SYS_rename __NR_rename
#define SYS_renameat __NR_renameat
#define SYS_renameat2 __NR_renameat2
#define SYS_request_key __NR_request_key
#define SYS_restart_syscall __NR_restart_syscall
#define SYS_rmdir __NR_rmdir
#define SYS_rt_sigaction __NR_rt_sigaction
#define SYS_rt_sigpending __NR_rt_sigpending
#define SYS_rt_sigprocmask __NR_rt_sigprocmask
#define SYS_rt_sigqueueinfo __NR_rt_sigqueueinfo
#define SYS_rt_sigreturn __NR_rt_sigreturn
#define SYS_rt_sigsuspend __NR_rt_sigsuspend
#define SYS_rt_sigtimedwait __NR_rt_sigtimedwait
#define SYS_rt_tgsigqueueinfo __NR_rt_tgsigqueueinfo
#define SYS_sched_get_priority_max __NR_sched_get_priority_max
#define SYS_sched_get_priority_min __NR_sched_get_priority_min
#define SYS_sched_getaffinity __NR_sched_getaffinity
#define SYS_sched_getattr __NR_sched_getattr
#define SYS_sched_getparam __NR_sched_getparam
#define SYS_sched_getscheduler __NR_sched_getscheduler
#define SYS_sched_rr_get_interval __NR_sched_rr_get_interval
#define SYS_sched_setaffinity __NR_sched_setaffinity
#define SYS_sched_setattr __NR_sched_setattr
#define SYS_sched_setparam __NR_sched_setparam
#define SYS_sched_setscheduler __NR_sched_setscheduler
#define SYS_sched_yield __NR_sched_yield
#define SYS_seccomp __NR_seccomp
#define SYS_security __NR_security
#define SYS_select __NR_select
#define SYS_semctl __NR_semctl
#define SYS_semget __NR_semget
#define SYS_semop __NR_semop
#define SYS_semtimedop __NR_semtimedop
#define SYS_sendfile __NR_sendfile
#define SYS_sendmmsg __NR_sendmmsg
#define SYS_sendmsg __NR_sendmsg
#define SYS_sendto __NR_sendto
#define SYS_set_mempolicy __NR_set_mempolicy
#define SYS_set_robust_list __NR_set_robust_list
#define SYS_set_thread_area __NR_set_thread_area
#define SYS_set_tid_address __NR_set_tid_address
#define SYS_setdomainname __NR_setdomainname
#define SYS_setfsgid __NR_setfsgid
#define SYS_setfsuid __NR_setfsuid
#define SYS_setgid __NR_setgid
#define SYS_setgroups __NR_setgroups
#define SYS_sethostname __NR_sethostname
#define SYS_setitimer __NR_setitimer
#define SYS_setns __NR_setns
#define SYS_setpgid __NR_setpgid
#define SYS_setpriority __NR_setpriority
#define SYS_setregid __NR_setregid
#define SYS_setresgid __NR_setresgid
#define SYS_setresuid __NR_setresuid
#define SYS_setreuid __NR_setreuid
#define SYS_setrlimit __NR_setrlimit
#define SYS_setsid __NR_setsid
#define SYS_setsockopt __NR_setsockopt
#define SYS_settimeofday __NR_settimeofday
#define SYS_setuid __NR_setuid
#define SYS_setxattr __NR_setxattr
#define SYS_shmat __NR_shmat
#define SYS_shmctl __NR_shmctl
#define SYS_shmdt __NR_shmdt
#define SYS_shmget __NR_shmget
#define SYS_shutdown __NR_shutdown
#define SYS_sigaltstack __NR_sigaltstack
#define SYS_signalfd __NR_signalfd
#define SYS_signalfd4 __NR_signalfd4
#define SYS_socket __NR_socket
#define SYS_socketpair __NR_socketpair
#define SYS_splice __NR_splice
#define SYS_stat __NR_stat
#define SYS_statfs __NR_statfs
#define SYS_swapoff __NR_swapoff
#define SYS_swapon __NR_swapon
#define SYS_symlink __NR_symlink
#define SYS_symlinkat __NR_symlinkat
#define SYS_sync __NR_sync
#define SYS_sync_file_range __NR_sync_file_range
#define SYS_syncfs __NR_syncfs
#define SYS_sysfs __NR_sysfs
#define SYS_sysinfo __NR_sysinfo
#define SYS_syslog __NR_syslog
#define SYS_tee __NR_tee
#define SYS_tgkill __NR_tgkill
#define SYS_time __NR_time
#define SYS_timer_create __NR_timer_create
#define SYS_timer_delete __NR_timer_delete
#define SYS_timer_getoverrun __NR_timer_getoverrun
#define SYS_timer_gettime __NR_timer_gettime
#define SYS_timer_settime __NR_timer_settime
#define SYS_timerfd_create __NR_timerfd_create
#define SYS_timerfd_gettime __NR_timerfd_gettime
#define SYS_timerfd_settime __NR_timerfd_settime
#define SYS_times __NR_times
#define SYS_tkill __NR_tkill
#define SYS_truncate __NR_truncate
#define SYS_tuxcall __NR_tuxcall
#define SYS_umask __NR_umask
#define SYS_umount2 __NR_umount2
#define SYS_uname __NR_uname
#define SYS_unlink __NR_unlink
#define SYS_unlinkat __NR_unlinkat
#define SYS_unshare __NR_unshare
#define SYS_uselib __NR_uselib
#define SYS_userfaultfd __NR_userfaultfd
#define SYS_ustat __NR_ustat
#define SYS_utime __NR_utime
#define SYS_utimensat __NR_utimensat
#define SYS_utimes __NR_utimes
#define SYS_vfork __NR_vfork
#define SYS_vhangup __NR_vhangup
#define SYS_vmsplice __NR_vmsplice
#define SYS_vserver __NR_vserver
#define SYS_wait4 __NR_wait4
#define SYS_waitid __NR_waitid
#define SYS_write __NR_write
#define SYS_writev __NR_writev
*/